/* Generated by wayland-scanner 1.24.0 */

/*
 * Copyright 2016 The Chromium Authors.
 * Copyright 2017 Intel Corporation
 * Copyright 2018 Collabora, Ltd
 * Copyright 2021 Simon Ser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface wp_linux_drm_syncobj_surface_v1_interface;
extern const struct wl_interface wp_linux_drm_syncobj_timeline_v1_interface;

static const struct wl_interface *linux_drm_syncobj_v1_types[] = {
	&wp_linux_drm_syncobj_surface_v1_interface,
	&wl_surface_interface,
	&wp_linux_drm_syncobj_timeline_v1_interface,
	NULL,
	&wp_linux_drm_syncobj_timeline_v1_interface,
	NULL,
	NULL,
	&wp_linux_drm_syncobj_timeline_v1_interface,
	NULL,
	NULL,
};

static const struct wl_message wp_linux_drm_syncobj_manager_v1_requests[] = {
	{ "destroy", "", linux_drm_syncobj_v1_types + 0 },
	{ "get_surface", "no", linux_drm_syncobj_v1_types + 0 },
	{ "import_timeline", "nh", linux_drm_syncobj_v1_types + 2 },
};

WL_PRIVATE const struct wl_interface wp_linux_drm_syncobj_manager_v1_interface = {
	"wp_linux_drm_syncobj_manager_v1", 1,
	3, wp_linux_drm_syncobj_manager_v1_requests,
	0, NULL,
};

static const struct wl_message wp_linux_drm_syncobj_timeline_v1_requests[] = {
	{ "destroy", "", linux_drm_syncobj_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface wp_linux_drm_syncobj_timeline_v1_interface = {
	"wp_linux_drm_syncobj_timeline_v1", 1,
	1, wp_linux_drm_syncobj_timeline_v1_requests,
	0, NULL,
};

static const struct wl_message wp_linux_drm_syncobj_surface_v1_requests[] = {
	{ "destroy", "", linux_drm_syncobj_v1_types + 0 },
	{ "set_acquire_point", "ouu", linux_drm_syncobj_v1_types + 4 },
	{ "set_release_point", "ouu", linux_drm_syncobj_v1_types + 7 },
};

WL_PRIVATE const struct wl_interface wp_linux_drm_syncobj_surface_v1_interface = {
	"wp_linux_drm_syncobj_surface_v1", 1,
	3, wp_linux_drm_syncobj_surface_v1_requests,
	0, NULL,
};

