#ifndef LDATASOURCE_H
#define LDATASOURCE_H

#include <LObject.h>
#include <bits/types/FILE.h>

/*!
 * @brief Data source exchanged between clients
 *
 * The LDataSource class represents the [wl_data_source](https://wayland.app/protocols/wayland#wl_data_source) interface of the Wayland protocol.
 * It is created by clients to define information that can be shared with other clients through the clipboard or in drag & drop sessions.\n
 *
 * See the LDataDevice and LDataOffer classes documentation for more information.
 */
class Louvre::LDataSource : LObject
{
public:   

    /*!
     * @brief Variant of a data source.
     *
     * Provides access to the information of data source for a specific mime type.\n
     */
    struct LSource
    {
        /// @brief File descriptor for a specific mime type
        FILE *tmp;

        /// @brief Mime type
        char *mimeType;
    };

    LDataSource(const LDataSource&) = delete;
    LDataSource& operator= (const LDataSource&) = delete;

    /*!
     * @brief Client owner of the data source.
     */
    LClient *client() const;

    /*!
     * @brief List of data source file descriptors.
     *
     * List of data source file descriptors for specific mime types.
     */
    const std::list<LSource>&sources() const;

    // Since 3

    /*!
     * @brief Actions available for drag & drop sessions.
     *
     * Bitfield indicating the actions available for a drag & drop session.\n
     * Bitfield flags are described in LDNDManager::Action.
     */
    UInt32 dndActions() const;

    /*!
     * @brief Wayland resource of the data source.
     *
     * @returns the resource generated by the [wl_data_source](https://wayland.app/protocols/wayland#wl_data_source) interface of the Wayland protocol.
     */
    Protocols::Wayland::RDataSource *dataSourceResource() const;

    LPRIVATE_IMP(LDataSource)

    friend class Protocols::Wayland::RDataSource;
    friend class Protocols::Wayland::RDataDevice;
    LDataSource(Protocols::Wayland::RDataSource *dataSourceResource);
    ~LDataSource();
};

#endif // LDATASOURCE_H
