#ifndef LDNDMANAGER_H
#define LDNDMANAGER_H

#include <LObject.h>

/*!
 * @brief Class for handling drag & drop sessions
 *
 * The LDNDManager class provides control over drag & drop sessions and can be accessed with LSeat::dndManager().\n
 * It has virtual methods that notify when a client wants to start or cancel a session, methods for
 * "drop" or cancel a data offering, and so on...
 */
class Louvre::LDNDManager : public LObject
{
public:
    struct Params;

    /*!
     * @brief Constructor of the LDNDManager class.
     *
     * There is a single instance of LDNDManager, which can be accessed from LSeat::dndManager().
     *
     * @param params Internal library parameters passed in the LCompositor::createDNDManagerRequest() virtual constructor.
     */
    LDNDManager(Params *params);

    /*!
     * @brief Destructor of the LDNDManager class.
     *
     * Invoked internally by the library after LCompositor::destroyDNDManagerRequest() is called.
     */
    virtual ~LDNDManager();

    LDNDManager(const LDNDManager&) = delete;
    LDNDManager& operator= (const LDNDManager&) = delete;

    /*!
     * @brief Action flags for drag & drop sessions.
     *
     * Clients who start drag & drop sessions or receive a data offer notify which actions they support.\n
     * For example, when dragging a file from a file manager window to another, the desired action might be to
     * move or copy the file.\n
     * The library by default performs a match of actions supported by the source and destination client, giving preference
     * to the first one listed in the enum, except for NoAction.\n
     * You can also select a different preferred action using the LDNDManager::setPreferredAction() method.
     */
    enum Action : UInt32
    {
        /// No preferred action
        NoAction = 0,

        /// The preferred action is to copy
        Copy = 1,

        /// The preferred action is to move
        Move = 2,

        /// The destination client asks the source client the preferred action
        Ask = 4
    };

    /*!
     * @brief Drag & drop session icon.
     *
     * LDNDIconRole of the surface used as drag & drop icon.\n
     *
     * @warning Not all drag & drop sessions use an icon.
     *
     * @returns nullptr if there is no session going on, or if the source client did not assign an icon.
     */
    LDNDIconRole *icon() const;

    /*!
     * @brief Surface that originates the drag & drop session.
     *
     * Surface from which the drag & drop session originates.
     *
     * @returns nullptr if there is no session going on.
     */
    LSurface *origin() const;

    /*!
     * @brief Focused surface.
     *
     * Surface to which the data offer is being presented to.\n
     * It typically is the surface located under the cursor.
     *
     * @returns nullptr if there is no session going on or if no surface has focus.
     */
    LSurface *focus() const;

    /*!
     * @brief Data source.
     *
     * Data source of the session, generated by the source client.
     *
     * @returns nullptr if there is no session going on.
     */
    LDataSource *source() const;

    LClient *dstClient() const;

    /*!
     * @brief Indicates if there is an ongoing drag & drop session.
     */
    bool dragging() const;

    /*!
     * @brief Cancels the session.
     *
     * Cancels the current drag & drop session.\n
     * If there is no session going on, calling this method is a no-op.
     */
    void cancel();

    /*!
     * @brief Drop the data offer.
     *
     * Drop the data offer on the surface with active focus and ends the session.\n
     * The destination client then exchanges the information with the source client, using the specified action.\n
     * If there is no focused surface, the session is cancelled.
     *
     * The library invokes this method when the left mouse button is released (check the default implementation of LPointer::pointerButtonEvent()).
     */
    void drop();

#if LOUVRE_DATA_DEVICE_MANAGER_VERSION >= 3

    /*!
     * @brief Preferred actions of the destination client.
     *
     * Bitfield with the preferred actions of the destination client.\n
     * Actions supported by the source client can be accessed in LDNDManager::source().
     */
    Action preferredAction() const;

    /*!
     * @brief Assigns the preferred action.
     *
     * Assigns the preferred action for the session. The library by default assigns the "move" action when holding down the **Shift** key and the "copy" action when holding down 
     * the **Ctrl** key (check the default implementation of LKeyboard::keyEvent()).\n
     * If the specified action is not supported by the source and destination client calling this method is a no-op.
     */
    void setPreferredAction(Action action);
#endif

    /*!
     * @brief Request to start a drag & drop session
     *
     * Reimplement this virtual method if you want to be notified when a client wants to start a drag & drop session.\n
     * This method is invoked only when there is no session in progress.\n
     * The default implementation validates that the client that originates the request has a surface with keyboard or pointer focus. If
     * neither condition is met the session is cancelled.
     *
     * #### Default implementation
     * @snippet LDNDManagerDefault.cpp startDragRequest
     */
    virtual void startDragRequest();

    /*!
     * @brief Notifies the cancellation of a session
     *
     * Reimplement this virtual method if you want to be notified when a drag & drop session is cancelled.\n
     * The default implementation repaints outputs where the drag & drop was visible.
     *
     * #### Default implementation
     * @snippet LDNDManagerDefault.cpp cancelled
     */
    virtual void cancelled();

    LPRIVATE_IMP(LDNDManager)
};

#endif // LDNDMANAGER_H
