/* Generated by wayland-scanner 1.23.0 */

#ifndef LVR_INVISIBLE_REGION_CLIENT_PROTOCOL_H
#define LVR_INVISIBLE_REGION_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_lvr_invisible_region The lvr_invisible_region protocol
 * invisible region of surfaces
 *
 * @section page_desc_lvr_invisible_region Description
 *
 * Warning: This protocol is experimental, and backward-incompatible changes may be 
 * made in the future.
 *
 * @section page_ifaces_lvr_invisible_region Interfaces
 * - @subpage page_iface_lvr_invisible_region_manager - invisible region manager
 * - @subpage page_iface_lvr_invisible_region - invisible region object
 * @section page_copyright_lvr_invisible_region Copyright
 * <pre>
 *
 * Copyright © 2025 Eduardo Hopperdietzel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct lvr_invisible_region;
struct lvr_invisible_region_manager;
struct wl_region;
struct wl_surface;

#ifndef LVR_INVISIBLE_REGION_MANAGER_INTERFACE
#define LVR_INVISIBLE_REGION_MANAGER_INTERFACE
/**
 * @page page_iface_lvr_invisible_region_manager lvr_invisible_region_manager
 * @section page_iface_lvr_invisible_region_manager_desc Description
 *
 * This interface allows a compositor to announce support for invisible regions.
 * @section page_iface_lvr_invisible_region_manager_api API
 * See @ref iface_lvr_invisible_region_manager.
 */
/**
 * @defgroup iface_lvr_invisible_region_manager The lvr_invisible_region_manager interface
 *
 * This interface allows a compositor to announce support for invisible regions.
 */
extern const struct wl_interface lvr_invisible_region_manager_interface;
#endif
#ifndef LVR_INVISIBLE_REGION_INTERFACE
#define LVR_INVISIBLE_REGION_INTERFACE
/**
 * @page page_iface_lvr_invisible_region lvr_invisible_region
 * @section page_iface_lvr_invisible_region_desc Description
 *
 * This extension builds upon existing regions exposed in wl_surface, such as 
 * damage, opaque, and input regions.
 *
 * Clients may use this extension to inform the compositor which parts of the 
 * surface are fully transparent (alpha = 0), allowing the compositor to optimize 
 * rendering by skipping these regions.
 *
 * Clients must not assume that the compositor will always skip rendering the region 
 * and should still ensure that the actual content is invisible if that is the 
 * intended result.
 *
 * The invisible region does not affect damage handling. If new parts of the surface 
 * become invisible and are marked as such, the client must still damage them as usual.
 *
 * If the invisible region intersects the opaque region, the overlapping area is 
 * also treated as invisible.
 * @section page_iface_lvr_invisible_region_api API
 * See @ref iface_lvr_invisible_region.
 */
/**
 * @defgroup iface_lvr_invisible_region The lvr_invisible_region interface
 *
 * This extension builds upon existing regions exposed in wl_surface, such as 
 * damage, opaque, and input regions.
 *
 * Clients may use this extension to inform the compositor which parts of the 
 * surface are fully transparent (alpha = 0), allowing the compositor to optimize 
 * rendering by skipping these regions.
 *
 * Clients must not assume that the compositor will always skip rendering the region 
 * and should still ensure that the actual content is invisible if that is the 
 * intended result.
 *
 * The invisible region does not affect damage handling. If new parts of the surface 
 * become invisible and are marked as such, the client must still damage them as usual.
 *
 * If the invisible region intersects the opaque region, the overlapping area is 
 * also treated as invisible.
 */
extern const struct wl_interface lvr_invisible_region_interface;
#endif

#ifndef LVR_INVISIBLE_REGION_MANAGER_ERROR_ENUM
#define LVR_INVISIBLE_REGION_MANAGER_ERROR_ENUM
enum lvr_invisible_region_manager_error {
	/**
	 * the surface already has an associated lvr_invisible_region object
	 */
	LVR_INVISIBLE_REGION_MANAGER_ERROR_ALREADY_CONSTRUCTED = 0,
};
#endif /* LVR_INVISIBLE_REGION_MANAGER_ERROR_ENUM */

#define LVR_INVISIBLE_REGION_MANAGER_DESTROY 0
#define LVR_INVISIBLE_REGION_MANAGER_GET_INVISIBLE_REGION 1


/**
 * @ingroup iface_lvr_invisible_region_manager
 */
#define LVR_INVISIBLE_REGION_MANAGER_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_lvr_invisible_region_manager
 */
#define LVR_INVISIBLE_REGION_MANAGER_GET_INVISIBLE_REGION_SINCE_VERSION 1

/** @ingroup iface_lvr_invisible_region_manager */
static inline void
lvr_invisible_region_manager_set_user_data(struct lvr_invisible_region_manager *lvr_invisible_region_manager, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) lvr_invisible_region_manager, user_data);
}

/** @ingroup iface_lvr_invisible_region_manager */
static inline void *
lvr_invisible_region_manager_get_user_data(struct lvr_invisible_region_manager *lvr_invisible_region_manager)
{
	return wl_proxy_get_user_data((struct wl_proxy *) lvr_invisible_region_manager);
}

static inline uint32_t
lvr_invisible_region_manager_get_version(struct lvr_invisible_region_manager *lvr_invisible_region_manager)
{
	return wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region_manager);
}

/**
 * @ingroup iface_lvr_invisible_region_manager
 *
 * This doesn't destroy objects created with the manager.
 */
static inline void
lvr_invisible_region_manager_destroy(struct lvr_invisible_region_manager *lvr_invisible_region_manager)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_invisible_region_manager,
			 LVR_INVISIBLE_REGION_MANAGER_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region_manager), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_lvr_invisible_region_manager
 *
 * The surface must not already have an associated lvr_invisible_region object, otherwise, 
 * the already_constructed error will be emitted.
 */
static inline struct lvr_invisible_region *
lvr_invisible_region_manager_get_invisible_region(struct lvr_invisible_region_manager *lvr_invisible_region_manager, struct wl_surface *surface)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) lvr_invisible_region_manager,
			 LVR_INVISIBLE_REGION_MANAGER_GET_INVISIBLE_REGION, &lvr_invisible_region_interface, wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region_manager), 0, NULL, surface);

	return (struct lvr_invisible_region *) id;
}

#ifndef LVR_INVISIBLE_REGION_ERROR_ENUM
#define LVR_INVISIBLE_REGION_ERROR_ENUM
enum lvr_invisible_region_error {
	/**
	 * surface destroyed before its lvr_invisible_region object
	 */
	LVR_INVISIBLE_REGION_ERROR_DESTROYED_SURFACE = 0,
};
#endif /* LVR_INVISIBLE_REGION_ERROR_ENUM */

#define LVR_INVISIBLE_REGION_DESTROY 0
#define LVR_INVISIBLE_REGION_SET_REGION 1


/**
 * @ingroup iface_lvr_invisible_region
 */
#define LVR_INVISIBLE_REGION_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_lvr_invisible_region
 */
#define LVR_INVISIBLE_REGION_SET_REGION_SINCE_VERSION 1

/** @ingroup iface_lvr_invisible_region */
static inline void
lvr_invisible_region_set_user_data(struct lvr_invisible_region *lvr_invisible_region, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) lvr_invisible_region, user_data);
}

/** @ingroup iface_lvr_invisible_region */
static inline void *
lvr_invisible_region_get_user_data(struct lvr_invisible_region *lvr_invisible_region)
{
	return wl_proxy_get_user_data((struct wl_proxy *) lvr_invisible_region);
}

static inline uint32_t
lvr_invisible_region_get_version(struct lvr_invisible_region *lvr_invisible_region)
{
	return wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region);
}

/**
 * @ingroup iface_lvr_invisible_region
 *
 * Switch back to a mode with an empty invisible region at the next commit.
 *
 * Must be destroyed before its associated surface otherwise the
 * destroyed_surface error will be emitted.
 */
static inline void
lvr_invisible_region_destroy(struct lvr_invisible_region *lvr_invisible_region)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_invisible_region,
			 LVR_INVISIBLE_REGION_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_lvr_invisible_region
 *
 * The region is defined in local surface coordinates. The compositor will clip 
 * any portion that extends beyond the surface bounds.
 *
 * If the region is null, the entire surface is treated as invisible. Note that 
 * this does not imply the surface is unmapped.
 *
 * The region is double-buffered and changes take effect upon the next commit.
 *
 * The initial value is an empty region (non-null).
 */
static inline void
lvr_invisible_region_set_region(struct lvr_invisible_region *lvr_invisible_region, struct wl_region *region)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_invisible_region,
			 LVR_INVISIBLE_REGION_SET_REGION, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_invisible_region), 0, region);
}

#ifdef  __cplusplus
}
#endif

#endif
