/* Generated by wayland-scanner 1.23.0 */

#ifndef LVR_SVG_PATH_CLIENT_PROTOCOL_H
#define LVR_SVG_PATH_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_lvr_svg_path The lvr_svg_path protocol
 * vector shapes factory
 *
 * @section page_desc_lvr_svg_path Description
 *
 * This protocol provides an efficient way for clients to define complex shapes.
 *
 * One common use for these shapes is masking, as seen in the lvr_background_blur 
 * protocol. However, other protocols may apply them for purposes not covered in 
 * this document.
 *
 * Shapes are expressed as a string of SVG path commands, a standard and widely 
 * used format. In the future, this approach may be replaced by separate requests 
 * for each type of SVG path command.
 *
 * Warning: This protocol is experimental, and backward-incompatible changes may be 
 * made in the future.
 *
 * @section page_ifaces_lvr_svg_path Interfaces
 * - @subpage page_iface_lvr_svg_path_manager - SVG path manager
 * - @subpage page_iface_lvr_svg_path - SVG path object
 * @section page_copyright_lvr_svg_path Copyright
 * <pre>
 *
 * Copyright © 2025 Eduardo Hopperdietzel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct lvr_svg_path;
struct lvr_svg_path_manager;

#ifndef LVR_SVG_PATH_MANAGER_INTERFACE
#define LVR_SVG_PATH_MANAGER_INTERFACE
/**
 * @page page_iface_lvr_svg_path_manager lvr_svg_path_manager
 * @section page_iface_lvr_svg_path_manager_desc Description
 *
 * This interface allows a compositor to announce support for SVG paths.
 * @section page_iface_lvr_svg_path_manager_api API
 * See @ref iface_lvr_svg_path_manager.
 */
/**
 * @defgroup iface_lvr_svg_path_manager The lvr_svg_path_manager interface
 *
 * This interface allows a compositor to announce support for SVG paths.
 */
extern const struct wl_interface lvr_svg_path_manager_interface;
#endif
#ifndef LVR_SVG_PATH_INTERFACE
#define LVR_SVG_PATH_INTERFACE
/**
 * @page page_iface_lvr_svg_path lvr_svg_path
 * @section page_iface_lvr_svg_path_desc Description
 *
 * The SVG path is described as a string of commands, as outlined here:
 *
 * https://svgwg.org/specs/paths/
 *
 * After requesting a lvr_svg_path object, the client must send zero or multiple 
 * concat_commands if the string exceeds 4096 bytes, which is the default maximum 
 * length supported by libwayland. The compositor concatenates the strings in order 
 * of receipt. 
 *
 * Once all commands are sent, the client must issue a done request, at which point 
 * the SVG path is considered complete. Sending a done request without having previously 
 * sent a concat_command is valid and represents an empty path. 
 *
 * No requests, except for destroy, are accepted after a done event, otherwise, 
 * the already_constructed error is emitted.
 *
 * Sending a destroy request without having sent a done request triggers the incomplete error. 
 *
 * If the final string yield an invalid SVG path, the invalid_commands error is emitted. 
 *
 * The coordinate system of the described path depends on the context in which it is used.
 * @section page_iface_lvr_svg_path_api API
 * See @ref iface_lvr_svg_path.
 */
/**
 * @defgroup iface_lvr_svg_path The lvr_svg_path interface
 *
 * The SVG path is described as a string of commands, as outlined here:
 *
 * https://svgwg.org/specs/paths/
 *
 * After requesting a lvr_svg_path object, the client must send zero or multiple 
 * concat_commands if the string exceeds 4096 bytes, which is the default maximum 
 * length supported by libwayland. The compositor concatenates the strings in order 
 * of receipt. 
 *
 * Once all commands are sent, the client must issue a done request, at which point 
 * the SVG path is considered complete. Sending a done request without having previously 
 * sent a concat_command is valid and represents an empty path. 
 *
 * No requests, except for destroy, are accepted after a done event, otherwise, 
 * the already_constructed error is emitted.
 *
 * Sending a destroy request without having sent a done request triggers the incomplete error. 
 *
 * If the final string yield an invalid SVG path, the invalid_commands error is emitted. 
 *
 * The coordinate system of the described path depends on the context in which it is used.
 */
extern const struct wl_interface lvr_svg_path_interface;
#endif

#define LVR_SVG_PATH_MANAGER_DESTROY 0
#define LVR_SVG_PATH_MANAGER_GET_SVG_PATH 1


/**
 * @ingroup iface_lvr_svg_path_manager
 */
#define LVR_SVG_PATH_MANAGER_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_lvr_svg_path_manager
 */
#define LVR_SVG_PATH_MANAGER_GET_SVG_PATH_SINCE_VERSION 1

/** @ingroup iface_lvr_svg_path_manager */
static inline void
lvr_svg_path_manager_set_user_data(struct lvr_svg_path_manager *lvr_svg_path_manager, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) lvr_svg_path_manager, user_data);
}

/** @ingroup iface_lvr_svg_path_manager */
static inline void *
lvr_svg_path_manager_get_user_data(struct lvr_svg_path_manager *lvr_svg_path_manager)
{
	return wl_proxy_get_user_data((struct wl_proxy *) lvr_svg_path_manager);
}

static inline uint32_t
lvr_svg_path_manager_get_version(struct lvr_svg_path_manager *lvr_svg_path_manager)
{
	return wl_proxy_get_version((struct wl_proxy *) lvr_svg_path_manager);
}

/**
 * @ingroup iface_lvr_svg_path_manager
 *
 * Destroy the SVG path manager. This doesn't destroy objects created with the 
 * manager.
 */
static inline void
lvr_svg_path_manager_destroy(struct lvr_svg_path_manager *lvr_svg_path_manager)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_svg_path_manager,
			 LVR_SVG_PATH_MANAGER_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_svg_path_manager), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_lvr_svg_path_manager
 */
static inline struct lvr_svg_path *
lvr_svg_path_manager_get_svg_path(struct lvr_svg_path_manager *lvr_svg_path_manager)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) lvr_svg_path_manager,
			 LVR_SVG_PATH_MANAGER_GET_SVG_PATH, &lvr_svg_path_interface, wl_proxy_get_version((struct wl_proxy *) lvr_svg_path_manager), 0, NULL);

	return (struct lvr_svg_path *) id;
}

#ifndef LVR_SVG_PATH_ERROR_ENUM
#define LVR_SVG_PATH_ERROR_ENUM
enum lvr_svg_path_error {
	/**
	 * incomplete svg path
	 */
	LVR_SVG_PATH_ERROR_INCOMPLETE = 0,
	/**
	 * a request other than destroy was made after a done request
	 */
	LVR_SVG_PATH_ERROR_ALREADY_CONSTRUCTED = 1,
	/**
	 * the final string doesn't represent a valid svg path
	 */
	LVR_SVG_PATH_ERROR_INVALID_COMMANDS = 2,
};
#endif /* LVR_SVG_PATH_ERROR_ENUM */

#define LVR_SVG_PATH_DESTROY 0
#define LVR_SVG_PATH_CONCAT_COMMANDS 1
#define LVR_SVG_PATH_DONE 2


/**
 * @ingroup iface_lvr_svg_path
 */
#define LVR_SVG_PATH_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_lvr_svg_path
 */
#define LVR_SVG_PATH_CONCAT_COMMANDS_SINCE_VERSION 1
/**
 * @ingroup iface_lvr_svg_path
 */
#define LVR_SVG_PATH_DONE_SINCE_VERSION 1

/** @ingroup iface_lvr_svg_path */
static inline void
lvr_svg_path_set_user_data(struct lvr_svg_path *lvr_svg_path, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) lvr_svg_path, user_data);
}

/** @ingroup iface_lvr_svg_path */
static inline void *
lvr_svg_path_get_user_data(struct lvr_svg_path *lvr_svg_path)
{
	return wl_proxy_get_user_data((struct wl_proxy *) lvr_svg_path);
}

static inline uint32_t
lvr_svg_path_get_version(struct lvr_svg_path *lvr_svg_path)
{
	return wl_proxy_get_version((struct wl_proxy *) lvr_svg_path);
}

/**
 * @ingroup iface_lvr_svg_path
 *
 */
static inline void
lvr_svg_path_destroy(struct lvr_svg_path *lvr_svg_path)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_svg_path,
			 LVR_SVG_PATH_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_svg_path), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_lvr_svg_path
 *
 * The string size of each request must not exceed the 4096-byte limit.
 */
static inline void
lvr_svg_path_concat_commands(struct lvr_svg_path *lvr_svg_path, const char *commands)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_svg_path,
			 LVR_SVG_PATH_CONCAT_COMMANDS, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_svg_path), 0, commands);
}

/**
 * @ingroup iface_lvr_svg_path
 *
 * Once this request is sent, the only permissible action is destroy.
 */
static inline void
lvr_svg_path_done(struct lvr_svg_path *lvr_svg_path)
{
	wl_proxy_marshal_flags((struct wl_proxy *) lvr_svg_path,
			 LVR_SVG_PATH_DONE, NULL, wl_proxy_get_version((struct wl_proxy *) lvr_svg_path), 0);
}

#ifdef  __cplusplus
}
#endif

#endif
