name: Build docs

on: [workflow_dispatch]

jobs:
  build:
    name: Create docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run doxygen
        run: |
          cd scripts/docs
          chmod +x gen_doc.sh
          ./gen_doc.sh
          cd ../../

      - name: Upload docs
        run: |
          git config --global user.email "eduardo.hopperdietzel@alumnos.uach.cl"
          git config --global user.name "Eduardo Hopperdietzel"
          git checkout -b docs
          rm -r *
          rm -r .github
          rm .gitignore
          cp -r ../louvre_tmp/html ./
          mv html docs
          git add .
          git commit -m "Doxygen"
          git push -f --set-upstream origin docs