name: Create new Louvre release

on: [workflow_dispatch]

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set ENV
        id: set-env
        run: |
          cd scripts
          chmod +x env.sh
          source env.sh

          echo "DEB pkg name: $LOUVRE_DEB_PACKAGE_NAME"
          echo "RPM pkg name: $LOUVRE_RPM_PACKAGE_NAME"
          echo "DEB pkg arch: $LOUVRE_DEB_PACKAGE_ARCH"
          echo "RPM pkg arch: $LOUVRE_RPM_PACKAGE_ARCH"
          echo "Louvre version: $LOUVRE_VERSION"
          echo "Louvre build: $LOUVRE_BUILD"
          echo "Louvre changes: $LOUVRE_CHANGES"


          echo "LOUVRE_DEB_PACKAGE_NAME=$LOUVRE_DEB_PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "LOUVRE_RPM_PACKAGE_NAME=$LOUVRE_RPM_PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "LOUVRE_DEB_PACKAGE_ARCH=$LOUVRE_DEB_PACKAGE_ARCH" >> $GITHUB_OUTPUT
          echo "LOUVRE_RPM_PACKAGE_ARCH=$LOUVRE_RPM_PACKAGE_ARCH" >> $GITHUB_OUTPUT
          echo "LOUVRE_VERSION=$LOUVRE_VERSION" >> $GITHUB_OUTPUT
          echo "LOUVRE_BUILD=$LOUVRE_BUILD" >> $GITHUB_OUTPUT

          echo 'CHANGES<<EOF' >> $GITHUB_ENV
          echo "$LOUVRE_CHANGES" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          cd ..
      
      - name: Create .deb
        run: |
          cd scripts/packaging/deb
          chmod +x 01-install_deps.sh
          chmod +x 02-build_louvre.sh
          chmod +x 03-gen_package.sh
          ./01-install_deps.sh
          ./02-build_louvre.sh
          ./03-gen_package.sh
          cd ../../../
      - name: Create .rpm
        run: |
          cd scripts/packaging/rpm
          chmod +x gen_package.sh
          ./gen_package.sh
          cd ../../../
      - name: Create release
        id: crerel
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}
          release_name: Release v${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}
          body: ${{ env.CHANGES }}
          draft: false
          prerelease: false

      - name: Upload .deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.crerel.outputs.upload_url }}
          asset_path: ../louvre_tmp/packages/${{ steps.set-env.outputs.LOUVRE_DEB_PACKAGE_NAME }}-${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}.deb
          asset_name: ${{ steps.set-env.outputs.LOUVRE_DEB_PACKAGE_NAME }}-${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}.${{ steps.set-env.outputs.LOUVRE_DEB_PACKAGE_ARCH }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload .rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.crerel.outputs.upload_url }}
          asset_path: ../louvre_tmp/packages/${{ steps.set-env.outputs.LOUVRE_RPM_PACKAGE_NAME }}-${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}.${{ steps.set-env.outputs.LOUVRE_RPM_PACKAGE_ARCH }}.rpm
          asset_name: ${{ steps.set-env.outputs.LOUVRE_RPM_PACKAGE_NAME }}-${{ steps.set-env.outputs.LOUVRE_VERSION }}-${{ steps.set-env.outputs.LOUVRE_BUILD }}.${{ steps.set-env.outputs.LOUVRE_RPM_PACKAGE_ARCH }}.rpm
          asset_content_type: application/x-rpm
      

